[pytest]
testpaths = tests
norecursedirs = third_party src/third_party .*/ build/ dist/
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning:torch.distributed.optim
    ignore:.*TorchScript.*support for functional optimizers is deprecated.*:DeprecationWarning
